[build]
builder = "nixpacks"
buildCommand = "rm -rf dist tsconfig.build.tsbuildinfo .env .env.* .next && npm i --legacy-peer-deps && npx prisma generate && npm run build"

[deploy]
startCommand = "npx prisma db push --accept-data-loss --skip-generate && npm run start:prod"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
