import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const vehicles = [
  {
    title: '2021 Toyota Camry SE',
    make: 'Toyota',
    model: 'Camry',
    year: 2021,
    priceAmount: 18500,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 45000,
    bodyType: 'Sedan',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'FWD',
    vin: '4T1G11AK5MU123456',
    locationCountry: 'US',
    locationCity: 'Los Angeles',
    locationState: 'CA',
    specs: { engineVolume: '2.5L', enginePower: '203 hp', cylinders: '4', doors: '4', color: 'White' },
    media: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80',
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80',
    ],
    description: 'Toyota Camry SE 2021 року в чудовому стані. Економічний 2.5-літровий двигун, повний комплект електроніки, камера заднього виду, Apple CarPlay.',
  },
  {
    title: '2022 BMW X5 xDrive40i',
    make: 'BMW',
    model: 'X5',
    year: 2022,
    priceAmount: 42000,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 28000,
    bodyType: 'SUV',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: '5UXCR6C05N9B12345',
    locationCountry: 'US',
    locationCity: 'Houston',
    locationState: 'TX',
    specs: { engineVolume: '3.0L', enginePower: '335 hp', cylinders: '6', doors: '4', color: 'Black' },
    media: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
      'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&q=80',
    ],
    description: 'BMW X5 xDrive40i — преміальний кросовер з потужним 3.0 турбо. Панорамний дах, шкіряний салон, адаптивна підвіска, повний привід.',
  },
  {
    title: '2020 Tesla Model 3 Long Range',
    make: 'Tesla',
    model: 'Model 3',
    year: 2020,
    priceAmount: 24500,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 52000,
    bodyType: 'Sedan',
    fuelType: 'Electric',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: '5YJ3E1EA7LF123456',
    locationCountry: 'US',
    locationCity: 'San Francisco',
    locationState: 'CA',
    specs: { engineVolume: 'Electric', enginePower: '346 hp', cylinders: '-', doors: '4', color: 'Blue' },
    media: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80',
    ],
    description: 'Tesla Model 3 Long Range з автопілотом. Запас ходу ~500 км, повний привід, скляний дах, мінімальне обслуговування.',
  },
  {
    title: '2023 Mercedes-Benz GLE 350',
    make: 'Mercedes-Benz',
    model: 'GLE 350',
    year: 2023,
    priceAmount: 48000,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 15000,
    bodyType: 'SUV',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: 'W1N0G8DB2PA123456',
    locationCountry: 'US',
    locationCity: 'Miami',
    locationState: 'FL',
    specs: { engineVolume: '2.0L', enginePower: '255 hp', cylinders: '4', doors: '4', color: 'Silver' },
    media: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80',
    ],
    description: 'Mercedes-Benz GLE 350 — сучасний luxury SUV з MBUX мультимедіа, 64-кольоровим ambient-освітленням та повним пакетом безпеки.',
  },
  {
    title: '2021 Ford Mustang GT',
    make: 'Ford',
    model: 'Mustang',
    year: 2021,
    priceAmount: 29000,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 32000,
    bodyType: 'Coupe',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'RWD',
    vin: '1FA6P8CF3M5123456',
    locationCountry: 'US',
    locationCity: 'Dallas',
    locationState: 'TX',
    specs: { engineVolume: '5.0L', enginePower: '460 hp', cylinders: '8', doors: '2', color: 'Red' },
    media: [
      'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=800&q=80',
    ],
    description: 'Ford Mustang GT з легендарним V8 5.0 Coyote. 460 к.с., спортивна підвіска, Brembo гальма, активний випуск.',
  },
  {
    title: '2022 Hyundai Tucson SEL',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    priceAmount: 22000,
    sourceType: 'INTERNAL',
    sourceRegion: 'USA',
    odometerValue: 38000,
    bodyType: 'SUV',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: '5NMJFDAF1NH123456',
    locationCountry: 'UA',
    locationCity: 'Рівне',
    specs: { engineVolume: '2.5L', enginePower: '187 hp', cylinders: '4', doors: '4', color: 'Gray' },
    media: [
      'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=800&q=80',
    ],
    description: 'Hyundai Tucson нового покоління. Стильний дизайн, двозонний клімат, 10.25" екран, повний привід.',
  },
  {
    title: '2020 Audi Q7 Premium Plus',
    make: 'Audi',
    model: 'Q7',
    year: 2020,
    priceAmount: 35000,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 55000,
    bodyType: 'SUV',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: 'WA1LAAF79LD012345',
    locationCountry: 'US',
    locationCity: 'Atlanta',
    locationState: 'GA',
    specs: { engineVolume: '3.0L', enginePower: '261 hp', cylinders: '6', doors: '4', color: 'White' },
    media: [
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=800&q=80',
    ],
    description: 'Audi Q7 Premium Plus — 7-місний сімейний кросовер з Quattro повним приводом, Virtual Cockpit та B&O аудіосистемою.',
  },
  {
    title: '2023 Kia EV6 Wind',
    make: 'Kia',
    model: 'EV6',
    year: 2023,
    priceAmount: 31000,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 12000,
    bodyType: 'Hatchback',
    fuelType: 'Electric',
    transmission: 'Automatic',
    driveType: 'RWD',
    vin: 'KNDC3DLC5P5012345',
    locationCountry: 'US',
    locationCity: 'Portland',
    locationState: 'OR',
    specs: { engineVolume: 'Electric', enginePower: '225 hp', cylinders: '-', doors: '4', color: 'Green' },
    media: [
      'https://images.unsplash.com/photo-1504215680853-026ed2a45def?w=800&q=80',
    ],
    description: 'Kia EV6 — електрокросовер на платформі E-GMP. Ультра-швидка зарядка 18 хв (10-80%), запас ходу 440 км.',
  },
  {
    title: '2019 Lexus RX 350',
    make: 'Lexus',
    model: 'RX 350',
    year: 2019,
    priceAmount: 27500,
    sourceType: 'INTERNAL',
    sourceRegion: 'UKRAINE',
    odometerValue: 68000,
    bodyType: 'SUV',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: '2T2BZMCA5KC123456',
    locationCountry: 'UA',
    locationCity: 'Тернопіль',
    specs: { engineVolume: '3.5L', enginePower: '295 hp', cylinders: '6', doors: '4', color: 'Black' },
    media: [
      'https://images.unsplash.com/photo-1619405399517-d7fce0f13302?w=800&q=80',
    ],
    description: 'Lexus RX 350 — преміальний комфортний кросовер. Японська надійність, шкіряний салон Mark Levinson аудіо.',
  },
  {
    title: '2022 Chevrolet Camaro LT1',
    make: 'Chevrolet',
    model: 'Camaro',
    year: 2022,
    priceAmount: 26000,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 22000,
    bodyType: 'Coupe',
    fuelType: 'Gasoline',
    transmission: 'Manual',
    driveType: 'RWD',
    vin: '1G1FE1R72N0123456',
    locationCountry: 'US',
    locationCity: 'Chicago',
    locationState: 'IL',
    specs: { engineVolume: '6.2L', enginePower: '455 hp', cylinders: '8', doors: '2', color: 'Yellow' },
    media: [
      'https://images.unsplash.com/photo-1570356528233-b442cf2de345?w=800&q=80',
    ],
    description: 'Chevrolet Camaro LT1 з V8 6.2L. Механічна 6-ступка, Brembo гальма, магнітна підвіска, Head-Up дисплей.',
  },
  {
    title: '2021 Honda CR-V EX-L',
    make: 'Honda',
    model: 'CR-V',
    year: 2021,
    priceAmount: 23000,
    sourceType: 'INTERNAL',
    sourceRegion: 'USA',
    odometerValue: 41000,
    bodyType: 'SUV',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: '7FARW2H82ME123456',
    locationCountry: 'US',
    locationCity: 'Newark',
    locationState: 'NJ',
    specs: { engineVolume: '1.5L', enginePower: '190 hp', cylinders: '4', doors: '4', color: 'Blue' },
    media: [
      'https://images.unsplash.com/photo-1568844293986-8d0400bd4745?w=800&q=80',
    ],
    description: 'Honda CR-V EX-L — надійний компактний кросовер. Турбо 1.5, шкіряний салон, Honda Sensing, відмінна економічність.',
  },
  {
    title: '2023 Volkswagen ID.4 Pro S',
    make: 'Volkswagen',
    model: 'ID.4',
    year: 2023,
    priceAmount: 28000,
    sourceType: 'COPART',
    sourceRegion: 'EUROPE',
    odometerValue: 18000,
    bodyType: 'SUV',
    fuelType: 'Electric',
    transmission: 'Automatic',
    driveType: 'RWD',
    vin: 'WVGDMPE27PP012345',
    locationCountry: 'DE',
    locationCity: 'Berlin',
    specs: { engineVolume: 'Electric', enginePower: '201 hp', cylinders: '-', doors: '4', color: 'White' },
    media: [
      'https://images.unsplash.com/photo-1514316454349-750a7fd3da3a?w=800&q=80',
    ],
    description: 'Volkswagen ID.4 з Європи. Запас ходу 443 км, 12" дисплей, IQ.Drive асистенти, просторий салон.',
  },
  {
    title: '2020 Mazda CX-5 Grand Touring',
    make: 'Mazda',
    model: 'CX-5',
    year: 2020,
    priceAmount: 21000,
    sourceType: 'INTERNAL',
    sourceRegion: 'UKRAINE',
    odometerValue: 58000,
    bodyType: 'SUV',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: 'JM3KFBDM5L0123456',
    locationCountry: 'UA',
    locationCity: 'Рівне',
    specs: { engineVolume: '2.5L', enginePower: '187 hp', cylinders: '4', doors: '4', color: 'Red' },
    media: [
      'https://images.unsplash.com/photo-1493238792000-8113da705763?w=800&q=80',
    ],
    description: 'Mazda CX-5 Grand Touring — водійський кросовер з преміальним салоном. KODO дизайн, Bose аудіо, шкіра Nappa.',
  },
  {
    title: '2022 Dodge Charger R/T',
    make: 'Dodge',
    model: 'Charger',
    year: 2022,
    priceAmount: 32000,
    sourceType: 'COPART',
    sourceRegion: 'USA',
    odometerValue: 25000,
    bodyType: 'Sedan',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'RWD',
    vin: '2C3CDXCT5NH123456',
    locationCountry: 'US',
    locationCity: 'Phoenix',
    locationState: 'AZ',
    specs: { engineVolume: '5.7L', enginePower: '370 hp', cylinders: '8', doors: '4', color: 'Black' },
    media: [
      'https://images.unsplash.com/photo-1612544448445-b8232cff3b6c?w=800&q=80',
    ],
    description: 'Dodge Charger R/T з HEMI V8. Потужний маслкар на кожен день — 4 двері, 370 к.с., активний випуск.',
  },
  {
    title: '2021 Subaru Outback Limited',
    make: 'Subaru',
    model: 'Outback',
    year: 2021,
    priceAmount: 24000,
    sourceType: 'INTERNAL',
    sourceRegion: 'USA',
    odometerValue: 47000,
    bodyType: 'Wagon',
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    driveType: 'AWD',
    vin: '4S4BTANC5M3123456',
    locationCountry: 'US',
    locationCity: 'Denver',
    locationState: 'CO',
    specs: { engineVolume: '2.5L', enginePower: '182 hp', cylinders: '4', doors: '4', color: 'Green' },
    media: [
      'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?w=800&q=80',
    ],
    description: 'Subaru Outback Limited — універсал для подорожей. Symmetrical AWD, EyeSight безпека, великий кліренс 220 мм.',
  },
];

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}

async function main() {
  console.log('🗑️  Clearing old vehicles...');
  await prisma.vehicleContentTranslation.deleteMany();
  await prisma.vehicleMedia.deleteMany();
  await prisma.vehicleSpec.deleteMany();
  await prisma.vehicleSourceBinding.deleteMany();
  await prisma.vehicle.deleteMany();

  console.log('🚗 Seeding vehicles...\n');

  for (const v of vehicles) {
    const slug = slugify(v.title) + '-' + Math.random().toString(36).slice(2, 6);

    const vehicle = await prisma.vehicle.create({
      data: {
        slug,
        title: v.title,
        make: v.make,
        model: v.model,
        year: v.year,
        priceAmount: v.priceAmount,
        currency: 'USD',
        sourceType: v.sourceType as any,
        sourceRegion: v.sourceRegion as any,
        publicationStatus: 'PUBLISHED',
        availabilityStatus: 'AVAILABLE',
        isRecommended: Math.random() > 0.5,
        vin: v.vin,
        odometerValue: v.odometerValue,
        bodyType: v.bodyType,
        fuelType: v.fuelType,
        transmission: v.transmission,
        driveType: v.driveType,
        locationCountry: v.locationCountry,
        locationCity: v.locationCity,
        locationState: v.locationState,
        publishedAt: new Date(),
        specs: {
          create: {
            engineVolume: v.specs.engineVolume,
            enginePower: v.specs.enginePower,
            cylinders: v.specs.cylinders,
            doors: v.specs.doors,
            color: v.specs.color,
          },
        },
        media: {
          create: v.media.map((url, i) => ({
            sourceUrl: url,
            mediaType: 'image',
            sortOrder: i,
            isPrimary: i === 0,
          })),
        },
        contentTranslations: {
          create: [
            {
              locale: 'uk',
              title: v.title,
              description: v.description,
            },
          ],
        },
      },
    });

    console.log(`  ✅ ${vehicle.title} (${vehicle.slug})`);
  }

  console.log(`\n🎉 Seeded ${vehicles.length} vehicles!`);
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
